# Generated by Django 3.2 on 2022-02-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_chapitre_nom_chapitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
